name: Update definitions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}

jobs:
  update-definitions:
    name: Update definitions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn --immutable
      - name: Update definitions
        run: yarn run refresh-kbs
      - name: Commit and PR changes
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: automatically update definitions"
          title: "chore: automatically update definitions"
          body: Update definitions from `[the-via/keyboards](https://github.com/the-via/keyboards)`
          branch: workflow/update-definitions